spring.application.name=api_pedidos

spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.zlwgspaehbbsvyhkhjly
spring.datasource.password=8KD76Pv+W_?D6h8

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=public
spring.flyway.enabled=true  
spring.flyway.schemas=public